services:

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  api: 
    image: pablolopez161616/s3-app:latest
    container_name: s3-app
    ports:
      - "8000:8000"
    environment:
      - LOCALSTACK_URL=http://localstack:4566
      - BUCKET_NAME=amzn-s3-bucket
      - AWS_ACCESS_KEY_ID=test        
      - AWS_SECRET_ACCESS_KEY=test    
      - AWS_DEFAULT_REGION=eu-south-2
    depends_on:
      localstack:
        condition: service_healthy